
import HeroSection from '@/organisms/HeroSection'
import Head from 'next/head'
import Image from 'next/image'
import { useState, useEffect } from 'react'
import React from 'react'

export default function Home({ hotelsData, overlayState, updateOverlayState }) {
  
  return (
    <>
      <Head>
        <title>Comwell - THE nr 1 hotel chain, hotels icon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <HeroSection hotelsData={hotelsData} overlayState={overlayState} updateOverlayState={updateOverlayState} />
      </main>
    </>
  )
}
